### ISSUE TITLE
iOS Desktop App Node Sync Time Error

### ISSUE THREAD

**Issue by jkspiffyman** [WhaleCoinOrg/DesktopWallet#2]
<img width="423" alt="screen shot 2017-11-23 at 11 41 08 pm" src="https://user-images.githubusercontent.com/33948982/33196953-e2b802c4-d0a7-11e7-99df-bd9c604ee656.png">
#### System information
``````
Version: `0.8.9`
OS & Version: osx
Node type: `
[node.log.files.zip](https://github.com/WhaleCoinOrg/DesktopWallet/files/1500726/node.log.files.zip)
gwhale(default)`
``````
Whale Coin Desktop iOS app not syncing with other nodes due to my computer's clock not being set automatically. My computer's clock and location are set automatically, yet I'm not syncing with the WhaleCoin network.

<img width="670" alt="screen shot 2017-11-23 at 11 45 25 pm" src="https://user-images.githubusercontent.com/33948982/33197014-6d73b534-d0a8-11e7-9410-6c6a9c231b39.png">

**Comment by hTrap** [comment]
I resolved this by clicking the unlock button at the bottom of the date and
time settings and then uncheck the set automatically check box and recheck
it again. Hopefully this should resolve the problem.

On Nov 24, 2017 11:17 AM, "jkspiffyman" <notifications@github.com> wrote:

[image: screen shot 2017-11-23 at 11 41 08 pm]
<https://user-images.githubusercontent.com/33948982/33196953-e2b802c4-d0a7-11e7-99df-bd9c604ee656.png>
#### System information `````` Version: `0.8.9` OS & Version: osx Node
type: ` [node.log.files.zip](https://github.com/WhaleCoinOrg/
DesktopWallet/files/1500726/node.log.files.zip) gwhale(default)` ``````
Whale Coin Desktop iOS app not syncing with other nodes due to my
computer's clock not being set automatically. My computer's clock and
location are set automatically, yet I'm not syncing with the WhaleCoin
network.

[image: screen shot 2017-11-23 at 11 45 25 pm]
<https://user-images.githubusercontent.com/33948982/33197014-6d73b534-d0a8-11e7-9410-6c6a9c231b39.png>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/WhaleCoinOrg/DesktopWallet/issues/2>, or mute the thread

**Comment by jkspiffyman** [comment]
I've tried that process while my Whale Desktop Wallet App is running and while it isn't running. Still get the error message. My app will say that the node is able to connect, but cannot find any peers to sync and does not display correct wallet balance.

**Comment by jkspiffyman** [comment]
Screen capture attached.

[osxWHL0.8.9ClockSync-GabeHodge480p.zip](https://github.com/WhaleCoinOrg/DesktopWallet/files/1533811/osxWHL0.8.9ClockSync-GabeHodge480p.zip)
